### ISSUE TITLE
Question: cperl and other perlish perls?

### ISSUE THREAD

**Issue by djzort** [gugod/App-perlbrew#501] opened 2016-02-01 04:22 UTC
Whats the consensus with allowing perlbrew to bring in cperl and other perlish perls?

**Comment by gugod** [comment] 2016-02-01 07:39
I would very much like to see the support of different perl distributions.

**Comment by ribasushi** [comment] 2016-05-19 17:18
@djzort As far as cperl is concerned - it is relatively easy, the problem is entirely within the `perlbrew` itself - it expects a very specific filename (in this case `cperl-cperl-$version.tar.gz`). I use [the following trivial workaround](https://github.com/dbsrgits/dbix-class/blob/c8b1011e/maint/travis-ci_scripts/20_install.bash#L34-L43), though it would be awesome to get things properly fixed in `perlbrew`

**Comment by gugod** [comment] 2016-05-23 19:48
I just pushed a commit to support installing cperl tarballs  to develop branch

https://github.com/gugod/App-perlbrew/commit/85cfa9fb8a55789ef55fbc69b63aa7090f8f6799

It made several assumption about of cperl release ( tarball names / dir names ) which I'm not very certain  at this point, because I only find one release. But once we detected that cperl is being installed, the flag `-Dusecperl` is implied, and that's probably the most important part.

**Comment by gugod** [comment] 2016-06-22 05:24
The 0.76 release supports cperl installation.

**Closed by gugod** 2016-06-22 05:24 UTC
