### ISSUE TITLE
Unclear error message

### ISSUE THREAD

**Issue by nigelhorne** [gugod/App-perlbrew#655] opened 2018-12-21 12:36 UTC
I can't work out why I'm seeing this:

`Not a CODE reference at /home/smoker/perl5/perlbrew/bin/perlbrew line 2615.`

Clearly I'm doing something wrong, but maybe perlbrew isn't validating data properly and as a result it's not telling me what.

**Comment by nigelhorne** [comment] 2018-12-21 12:38
If it helps, what I've recently done is changed my script to use the -Accflags option to install.

**Comment by Pascal666** [comment] 2018-12-22 04:16
Duplicate of #652

**Closed** 2020-10-24 04:10 UTC
